esphome:
  name: EPS
  friendly_name: EPS
  comment: Everything Presence sven
  name_add_mac_suffix: true
  project: 
    name: EverythingSmartTechnology.Everything Presence Lite
    version: "1.4.1"
  on_boot: 
    priority: -100
    then:
      - button.press: get_mmwave_firmware
      - binary_sensor.template.publish:
          id: zone1_occupancy
          state: false 
      - binary_sensor.template.publish:
          id: zone2_occupancy
          state: false 
      - binary_sensor.template.publish:
          id: zone3_occupancy
          state: false 
      - binary_sensor.template.publish:
          id: zone4_occupancy
          state: false

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:
  level: INFO

#Debugging
debug:
  update_interval: 10s
    
ota:
  - platform: esphome
    password: !secret wifi_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  output_power: 9.0 dB

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: " eps Fallback Hotspot"
    password: !secret wifi_password

web_server:
  port: 80
  include_internal: true

time:
  - platform: sntp
    id: time_now

packages:
  LD2450: github://sven3699/ep-test/esphome_ld2450.yaml
